// DON'T EDIT THIS FILE RUN `npx @iconoma/cli studio` TO UPDATE IT.
// IT IS GENERATED BY ICONOMA.
import * as React from "react";
import type { SVGProps } from "react";

// <iconoma-icon key="home" name="Home">
export const Home = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    stroke="currentColor"
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={2}
    viewBox="0 0 24 24"
    width="1em"
    height="1em"
    {...props}
  >
    <path d="M3 10.5 12 3l9 7.5" />
    <path d="M5 9.5V21h14V9.5" />
    <path d="M9 21v-7h6v7" />
  </svg>
);
// </iconoma-icon>

