// DON'T EDIT THIS FILE RUN `npx @iconoma/cli studio` TO UPDATE IT.
// IT IS GENERATED BY ICONOMA.
import * as React from "react";
import Svg, { Circle, Path } from "react-native-svg";
import type { SvgProps } from "react-native-svg";
const Clock = (props: SvgProps) => (
  <Svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth={2}
    strokeLinecap="round"
    strokeLinejoin="round"
    className="lucide lucide-alarm-clock-icon lucide-alarm-clock"
    width={24}
    height={24}
    {...props}
  >
    <Circle cx={12} cy={13} r={8} />
    <Path d="M12 9v4l2 2" />
    <Path d="M5 3 2 6" />
    <Path d="m22 6-3-3" />
    <Path d="M6.38 18.7 4 21" />
    <Path d="M17.64 18.67 20 21" />
  </Svg>
);
export default Clock;

