// DON'T EDIT THIS FILE RUN `npx @iconoma/cli studio` TO UPDATE IT.
// IT IS GENERATED BY ICONOMA.
import * as React from "react";
import Svg, { Circle, Path, Line } from "react-native-svg";
import type { SvgProps } from "react-native-svg";
const Happy = (props: SvgProps) => (
  <Svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth={2}
    strokeLinecap="round"
    strokeLinejoin="round"
    className="lucide lucide-laugh-icon lucide-laugh"
    width={24}
    height={24}
    {...props}
  >
    <Circle cx={12} cy={12} r={10} />
    <Path d="M18 13a6 6 0 0 1-6 5 6 6 0 0 1-6-5h12Z" />
    <Line x1={9} x2={9.01} y1={9} y2={9} />
    <Line x1={15} x2={15.01} y1={9} y2={9} />
  </Svg>
);
export default Happy;

